sudo: required
language: php
service: docker

before_install:
    - docker-compose build
    - docker-compose up -d
    - docker-compose exec php composer install

script:
    - make test

after_success:
    travis_retry docker-compose exec -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN php ./vendor/bin/php-coveralls -v
